version: '3'

services:
  database:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=discordBot
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
